### ISSUE TITLE
Transfer package name?

### ISSUE THREAD

**Issue by brucou** [den1n/xelement#1]
Hi @den1n I was wondering if I could use the `slim` package name (that I see belongs to you but is deprecated?). I see that you haven't been using for the last 7 years. Please let me know if that works with you. I'll be great to publish a state machine compiler that I am writing under that name. Of course, no big deal if you don't want to. Let me know, thanks!

**Comment by den1n** [comment]
Hello! I removed slim the package from the npm registry. Feel free to use
it.

ср, 6 мая 2020 г. в 08:19, brucou <notifications@github.com>:

**Comment by brucou** [comment]
Thank you!!
